sfdc:
  username: "![6BKHf3c3Wurt/msTG5/qtWOeVJzWiajb]"
  password: "![H7TyiPiE6RNae+DNO8d9Xg==]"
  token: "![jg9g477kjHgb4DBeWJU9KNnzjL8RnoUd5H4AAkeOs8M=]"
  url: "![obumAZd6l5dg18cygNBvoQ2OZ3vRnC6PCbbCY2aau1VfBV6w+WF9xXmPEM6wUmjGPtvVS3OYleQ=]"
http:
  host: "![4hUzB55NXH0=]"
  port: "![QALTuT+49+E=]"
  base_path: "![8XE6rx3Aw6k=]"