#%RAML 1.0
version: v1
title: Salesforce Case Attachment API

traits:
   client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

/attachment:
  post:
    is: [ client-id-required ]
    body: 
      multipart/form-data:
        properties: 
          file1: 
            description: The file to attach to case 
            required: true 
            type: file 
            fileTypes: [ 'image/jpeg']
          fileName:
            description: The name of the file attachment
            required: true
            type: string   
          fileEncoding:
            description: The encoding type for the file
            enum: ['binary','base64']
            required: true
          emailAddress:
            description: The email address of the contact
            required: true
    responses: 
      201:
        body: 
          application/json:
            example: |
              {
                "status": "success"
              }
      204:
        body: 
          application/json:
            example: |
              {
                "status": "no action"
              }